use array::ArrayTrait;
use orion::operators::tensor::core::{TensorTrait, Tensor, ExtraParams};
use orion::numbers::fixed_point::core::{FixedTrait, FixedType, FixedImpl};
use orion::operators::tensor::implementations::impl_tensor_fp::Tensor_fp;

fn output_0() -> Tensor<FixedType> {
    let mut shape = ArrayTrait::<usize>::new();
    shape.append(3);
    shape.append(3);
    shape.append(9);

    let mut data = ArrayTrait::new();
    data.append(FixedType { mag: 0, sign: false });
    data.append(FixedType { mag: 1, sign: false });
    data.append(FixedType { mag: 2, sign: false });
    data.append(FixedType { mag: 27, sign: false });
    data.append(FixedType { mag: 28, sign: false });
    data.append(FixedType { mag: 29, sign: false });
    data.append(FixedType { mag: 54, sign: false });
    data.append(FixedType { mag: 55, sign: false });
    data.append(FixedType { mag: 56, sign: false });
    data.append(FixedType { mag: 3, sign: false });
    data.append(FixedType { mag: 4, sign: false });
    data.append(FixedType { mag: 5, sign: false });
    data.append(FixedType { mag: 30, sign: false });
    data.append(FixedType { mag: 31, sign: false });
    data.append(FixedType { mag: 32, sign: false });
    data.append(FixedType { mag: 57, sign: false });
    data.append(FixedType { mag: 58, sign: false });
    data.append(FixedType { mag: 59, sign: false });
    data.append(FixedType { mag: 6, sign: false });
    data.append(FixedType { mag: 7, sign: false });
    data.append(FixedType { mag: 8, sign: false });
    data.append(FixedType { mag: 33, sign: false });
    data.append(FixedType { mag: 34, sign: false });
    data.append(FixedType { mag: 35, sign: false });
    data.append(FixedType { mag: 60, sign: false });
    data.append(FixedType { mag: 61, sign: false });
    data.append(FixedType { mag: 62, sign: false });
    data.append(FixedType { mag: 9, sign: false });
    data.append(FixedType { mag: 10, sign: false });
    data.append(FixedType { mag: 11, sign: false });
    data.append(FixedType { mag: 36, sign: false });
    data.append(FixedType { mag: 37, sign: false });
    data.append(FixedType { mag: 38, sign: false });
    data.append(FixedType { mag: 63, sign: false });
    data.append(FixedType { mag: 64, sign: false });
    data.append(FixedType { mag: 65, sign: false });
    data.append(FixedType { mag: 12, sign: false });
    data.append(FixedType { mag: 13, sign: false });
    data.append(FixedType { mag: 14, sign: false });
    data.append(FixedType { mag: 39, sign: false });
    data.append(FixedType { mag: 40, sign: false });
    data.append(FixedType { mag: 41, sign: false });
    data.append(FixedType { mag: 66, sign: false });
    data.append(FixedType { mag: 67, sign: false });
    data.append(FixedType { mag: 68, sign: false });
    data.append(FixedType { mag: 15, sign: false });
    data.append(FixedType { mag: 16, sign: false });
    data.append(FixedType { mag: 17, sign: false });
    data.append(FixedType { mag: 42, sign: false });
    data.append(FixedType { mag: 43, sign: false });
    data.append(FixedType { mag: 44, sign: false });
    data.append(FixedType { mag: 69, sign: false });
    data.append(FixedType { mag: 70, sign: false });
    data.append(FixedType { mag: 71, sign: false });
    data.append(FixedType { mag: 18, sign: false });
    data.append(FixedType { mag: 19, sign: false });
    data.append(FixedType { mag: 20, sign: false });
    data.append(FixedType { mag: 45, sign: false });
    data.append(FixedType { mag: 46, sign: false });
    data.append(FixedType { mag: 47, sign: false });
    data.append(FixedType { mag: 72, sign: false });
    data.append(FixedType { mag: 73, sign: false });
    data.append(FixedType { mag: 74, sign: false });
    data.append(FixedType { mag: 21, sign: false });
    data.append(FixedType { mag: 22, sign: false });
    data.append(FixedType { mag: 23, sign: false });
    data.append(FixedType { mag: 48, sign: false });
    data.append(FixedType { mag: 49, sign: false });
    data.append(FixedType { mag: 50, sign: false });
    data.append(FixedType { mag: 75, sign: false });
    data.append(FixedType { mag: 76, sign: false });
    data.append(FixedType { mag: 77, sign: false });
    data.append(FixedType { mag: 24, sign: false });
    data.append(FixedType { mag: 25, sign: false });
    data.append(FixedType { mag: 26, sign: false });
    data.append(FixedType { mag: 51, sign: false });
    data.append(FixedType { mag: 52, sign: false });
    data.append(FixedType { mag: 53, sign: false });
    data.append(FixedType { mag: 78, sign: false });
    data.append(FixedType { mag: 79, sign: false });
    data.append(FixedType { mag: 80, sign: false });

    let extra = ExtraParams { fixed_point: Option::Some(FixedImpl::FP16x16) };
    TensorTrait::new(shape.span(), data.span(), Option::Some(extra))
}