use array::{ArrayTrait, SpanTrait};
use orion::operators::tensor::{TensorTrait, Tensor};
use orion::operators::tensor::I32Tensor;
use orion::numbers::{IntegerTrait, i32};

fn output_0() -> Tensor<i32> {
    let mut shape = ArrayTrait::<usize>::new();
    shape.append(3);
    shape.append(4);
    shape.append(5);

    let mut data = ArrayTrait::new();
    data.append(i32 { mag: 113, sign: false });
    data.append(i32 { mag: 43, sign: false });
    data.append(i32 { mag: 31, sign: true });
    data.append(i32 { mag: 48, sign: false });
    data.append(i32 { mag: 69, sign: true });
    data.append(i32 { mag: 1, sign: true });
    data.append(i32 { mag: 40, sign: false });
    data.append(i32 { mag: 39, sign: false });
    data.append(i32 { mag: 118, sign: false });
    data.append(i32 { mag: 102, sign: true });
    data.append(i32 { mag: 37, sign: false });
    data.append(i32 { mag: 109, sign: true });
    data.append(i32 { mag: 78, sign: true });
    data.append(i32 { mag: 56, sign: true });
    data.append(i32 { mag: 77, sign: true });
    data.append(i32 { mag: 93, sign: true });
    data.append(i32 { mag: 107, sign: false });
    data.append(i32 { mag: 100, sign: true });
    data.append(i32 { mag: 110, sign: false });
    data.append(i32 { mag: 114, sign: false });
    data.append(i32 { mag: 42, sign: true });
    data.append(i32 { mag: 57, sign: false });
    data.append(i32 { mag: 52, sign: true });
    data.append(i32 { mag: 66, sign: true });
    data.append(i32 { mag: 94, sign: true });
    data.append(i32 { mag: 106, sign: true });
    data.append(i32 { mag: 21, sign: true });
    data.append(i32 { mag: 38, sign: true });
    data.append(i32 { mag: 89, sign: true });
    data.append(i32 { mag: 51, sign: true });
    data.append(i32 { mag: 57, sign: false });
    data.append(i32 { mag: 112, sign: false });
    data.append(i32 { mag: 35, sign: false });
    data.append(i32 { mag: 112, sign: true });
    data.append(i32 { mag: 18, sign: false });
    data.append(i32 { mag: 45, sign: false });
    data.append(i32 { mag: 37, sign: false });
    data.append(i32 { mag: 125, sign: true });
    data.append(i32 { mag: 56, sign: false });
    data.append(i32 { mag: 56, sign: false });
    data.append(i32 { mag: 72, sign: true });
    data.append(i32 { mag: 94, sign: true });
    data.append(i32 { mag: 74, sign: false });
    data.append(i32 { mag: 126, sign: true });
    data.append(i32 { mag: 49, sign: true });
    data.append(i32 { mag: 4, sign: false });
    data.append(i32 { mag: 63, sign: false });
    data.append(i32 { mag: 55, sign: false });
    data.append(i32 { mag: 21, sign: true });
    data.append(i32 { mag: 107, sign: true });
    data.append(i32 { mag: 100, sign: true });
    data.append(i32 { mag: 125, sign: true });
    data.append(i32 { mag: 119, sign: false });
    data.append(i32 { mag: 108, sign: false });
    data.append(i32 { mag: 112, sign: false });
    data.append(i32 { mag: 4, sign: false });
    data.append(i32 { mag: 67, sign: false });
    data.append(i32 { mag: 79, sign: true });
    data.append(i32 { mag: 99, sign: false });
    data.append(i32 { mag: 94, sign: false });
    TensorTrait::new(shape.span(), data.span())
}
